### ISSUE TITLE
Failed to start LoRa App Server.

### ISSUE THREAD

**Issue by VahrushevSA** [brocaar/loraserver#157] opened 2017-04-07 07:20 UTC
After version 0.5.0 I can not run Lora app server. I ask to help, what can be done.

**Comment by brocaar** [comment] 2017-04-07 07:33
Duplicate of https://github.com/brocaar/lora-app-server/issues/63

**Closed by brocaar** 2017-04-07 07:33 UTC

**Comment by vikkymahdrey** [comment] 2017-07-02 16:26
![screenshot from 2017-07-02 09-25-09](https://user-images.githubusercontent.com/21258814/27771675-4939141e-5f71-11e7-9a95-de71d687b9a3.png)

**Comment by vikkymahdrey** [comment] 2017-07-02 16:27
please help on this

**Comment by vikkymahdrey** [comment] 2017-07-02 16:55
I don't know exactly that i'm going correct way or not for generating jwt.
Please check here
![screenshot from 2017-07-02 09-53-12](https://user-images.githubusercontent.com/21258814/27771880-53f82ce2-5f75-11e7-8ba8-9516c8821159.png)

**Comment by vikkymahdrey** [comment] 2017-07-02 16:57
i'm taking JWT_SECRET=uAkvtgcPuaNxRubHA0g+OlS8ODFMkqJHRj+N700zzQY
This is the generated one.
Is this correct or not?

**Comment by vikkymahdrey** [comment] 2017-07-02 18:18
M using Ubuntu..
Now I configured loraserver and loraappserver
here m getting
![screenshot from 2017-07-02 11-14-05](https://user-images.githubusercontent.com/21258814/27772456-ae14a862-5f80-11e7-9f21-2bdcc780e20a.png)

But m not able to open loar-app-server web interface on http://localhost:8089
I configure Http_bind at localhost:8089 in /etc/default/lora-app-server
please check and help me

**Comment by sagar-patel-sls** [comment] 2018-10-05 06:08
1. start Lora-App-Server 
sudo /etc/init.d/lora-app-server [start|stop|restart|status]
OR
sudo systemctl [start|stop|restart|status] lora-app-server

2. access web interface using https://localhost:8089
