### ISSUE TITLE
how to setup key for Lora repo,following the docs results in keyserver timeout

### ISSUE THREAD

**Issue by 22karthik** [brocaar/loraserver#268] opened 2017-11-13 15:48 UTC

**Comment by brocaar** [comment] 2017-11-13 15:50
I'm closing this issue (again):

1. None of the asked questions were answered (e.g. commands to reproduce)
2. This is not a bug but a support question, please see https://forum.loraserver.io

**Closed by brocaar** 2017-11-13 15:50 UTC
